#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=70
STOP=75
 
start() {        
	cd /sd/promienko
	node app >>/sd/promienko.log 2>>/sd/promienko.err &
}                 
 
stop() {          
	kill -TERM `cat /sd/promienko/app.pid` node
	killall -TERM ssh
}
