#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=70
STOP=75
 
start() {        
	cd /root/promienko
	node app >>/sd/promienko.log 2>>&1 &
}                 
 
stop() {          
	kill -TERM `cat /sd/promienko/app.pid` node
	killall -TERM ssh
}
